name: COLCIC/UESC CI 

on: 
  workflow_dispatch:
    inputs:
       cli:
         description: Run by cypress command line
         default: yarn cypress run

  schedule:
    - cron:  '0 * * * *' # Executa a cada hora


jobs: 
  cypress-electron-tests:
     runs-on: ubuntu-latest
     steps: 
       - name: Get code
         uses: actions/checkout@v4.1.5

       - name: Install Dependencies
         run: yarn install  # Instala as dependências do projeto

       - name: Run Cypress tests
         run: ${{ github.event.inputs.cli }}   # Executa os testes Cypress com o comando fornecido
